project: 
  type: website
  output-dir: "." 

website:
  title: "Jake Nielsen"
  navbar:
    # background: "#1c4982"
    pinned: true
    left:
      - text: Blog
        href: blog-listing.qmd
      - text: Python data analysis
        menu: 
          - text: Pandas Basics
            href: pandas_basics.ipynb
          - text: Seaborn Basics
            href: seaborn_basics.ipynb
          # - text: Music Blog
            # href: Music_blog.ipynb
      - text: Project
        href: danl_proj_nba.ipynb
            
  page-footer: 
    center: "Powered with GitHub, Quarto, and Jupyter Notebook<br>© YOUR NAME, 2025"

format:
  html:
    theme: 
      light: flatly # flatly sandstone yeti united litera journal
      dark: darkly #  darkly cyborg slate solra superhero
    mainfont: system-ui; 
    highlight-style: atom-one  # atom-one espresso
    css: styles.css
    toc: false
    include-after-body: target_blank.html

